name: Deploy AstroJS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on Ubuntu server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 185.157.244.202
          username: etudiant
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 23016
          script: |
            set -e
            export PATH="$HOME/.bun/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

            echo "======================================"
            echo "Début du déploiement"
            echo "======================================"

            cd /var/www/scolarite/astro-scolarite-sqlite

            echo "Mise à jour du code..."
            git pull origin main

            echo "Installation des dépendances..."
            bun install

            echo "Compilation Astro..."
            bun run --bun build

            echo "Redémarrage de l'application..."
            sudo systemctl restart scolarite

            echo "Attente de 5 secondes pour laisser le serveur s'allumer..."
            sleep 5

            echo "Vérification du service..."
            sudo systemctl status scolarite

            echo "Health check..."
            curl --fail http://localhost:3333/

            echo "======================================"
            echo "Déploiement terminé"
            echo "======================================"